/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package coba;

import code.SetInfoClient;
import code.get_data;
import code.t_modelClient;
import code.testConnectionFtp;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import listData.dataClient;
import listData.dataServer;

/**
 *
 * @author Rootkit-Ltp
 */

public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    //inisial class di load
    dataClient d_listPC=new dataClient();
    dataServer d_listServer=new dataServer();
    SetInfoClient info= new SetInfoClient();
    
    String idSession;
    
    
    public Beranda() {
        initComponents();
        
        LayerGUI.moveToFront(beranda);
        dataClient.setVisible(false);
        dataServer.setVisible(false);
        bantuan.setVisible(false);
        Profile.setVisible(false);
        EditPath.setVisible(false);
        //pushLastUsed(null, null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayerGUI = new javax.swing.JLayeredPane();
        beranda = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_beranda_nama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bantuan = new javax.swing.JPanel();
        dataServer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_listServer = new javax.swing.JTable();
        btn_listServer = new javax.swing.JButton();
        dataClient = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_listClient = new javax.swing.JTable();
        btn_listClient = new javax.swing.JButton();
        Profile = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_profile_nama = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_profileNama = new javax.swing.JLabel();
        txt_profileEmail = new javax.swing.JLabel();
        txt_profileHP = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txt_profileFolder = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_profileFile = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_profileSize = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        EditPath = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txt_pathFolder = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        informasi = new javax.swing.JMenu();
        mnItem_profile = new javax.swing.JMenuItem();
        data = new javax.swing.JMenu();
        mnItem_komputer = new javax.swing.JMenuItem();
        mnItem_server = new javax.swing.JMenuItem();
        mnItem_archive = new javax.swing.JMenuItem();
        menu_bantuan = new javax.swing.JMenu();
        mnItem_bantuan = new javax.swing.JMenuItem();
        mnItem_aboutMe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cloud Storage Java Programming");
        setIconImages(null);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Last Action"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "IP", "Status", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/USer2.png"))); // NOI18N

        txt_beranda_nama.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_beranda_nama.setForeground(new java.awt.Color(255, 255, 255));
        txt_beranda_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_beranda_nama.setText("ROBERTUS NUGRAHA SETYA WAHYUDI");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Connected !!!");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status Storage Used");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("0.0 Mb");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_beranda_nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_beranda_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout berandaLayout = new javax.swing.GroupLayout(beranda);
        beranda.setLayout(berandaLayout);
        berandaLayout.setHorizontalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, berandaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        berandaLayout.setVerticalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        beranda.setBounds(0, 0, 1050, 510);
        LayerGUI.add(beranda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout bantuanLayout = new javax.swing.GroupLayout(bantuan);
        bantuan.setLayout(bantuanLayout);
        bantuanLayout.setHorizontalGroup(
            bantuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        bantuanLayout.setVerticalGroup(
            bantuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        bantuan.setBounds(0, 0, 1050, 510);
        LayerGUI.add(bantuan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_listServer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Ekstensi", "Tipe", "Besar", "Tanggal", "Jam Modify"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(t_listServer);

        btn_listServer.setText("List Server");
        btn_listServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataServerLayout = new javax.swing.GroupLayout(dataServer);
        dataServer.setLayout(dataServerLayout);
        dataServerLayout.setHorizontalGroup(
            dataServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataServerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_listServer)))
                .addContainerGap())
        );
        dataServerLayout.setVerticalGroup(
            dataServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataServerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listServer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataServer.setBounds(0, 0, 1050, 510);
        LayerGUI.add(dataServer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_listClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Tipe", "Besar", "Tanggal", "Modify"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t_listClient);

        btn_listClient.setText("Cek Client");
        btn_listClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataClientLayout = new javax.swing.GroupLayout(dataClient);
        dataClient.setLayout(dataClientLayout);
        dataClientLayout.setHorizontalGroup(
            dataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataClientLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_listClient)))
                .addContainerGap())
        );
        dataClientLayout.setVerticalGroup(
            dataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataClient.setBounds(0, 0, 1050, 510);
        LayerGUI.add(dataClient, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("ID Member"));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/USer2.png"))); // NOI18N

        txt_profile_nama.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        txt_profile_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_profile_nama.setText("ROBERTUS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_profile_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txt_profile_nama)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel8.setText("PROFILE PENGGUNA :");

        jLabel9.setText("Nama");

        jLabel10.setText("Email");

        jLabel12.setText("No Hp");

        jLabel13.setText(":");

        jLabel14.setText(":");

        jLabel16.setText(":");

        txt_profileNama.setText("txt_profileNama");

        txt_profileEmail.setText("txt_profileEMail");

        txt_profileHP.setText("txt_profileHP");

        txt_profileFolder.setText("txt_profileFolder");

        jLabel22.setText("Folder");

        jLabel24.setText("File");

        jLabel25.setText(":");

        txt_profileFile.setText("txt_profileFile");

        jLabel29.setText(":");

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel23.setText("JUMLAH DATA :");

        txt_profileSize.setText("txt_profileSize");

        jLabel27.setText(":");

        jLabel30.setText("Size");

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_profileNama)
                            .addComponent(txt_profileEmail)
                            .addComponent(txt_profileHP)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_profileFile)
                            .addComponent(txt_profileFolder)
                            .addComponent(txt_profileSize, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel23))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(txt_profileNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(txt_profileEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_profileHP)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel23)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel29)
                            .addComponent(txt_profileFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25)
                            .addComponent(txt_profileFolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel27)
                            .addComponent(txt_profileSize)))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        Profile.setBounds(0, 0, 1050, 510);
        LayerGUI.add(Profile, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setText("Ini merupakan halaman yang digunakan untuk melakukan pengeditan path / lokasi folder yang digunakan pada Aplikasi Cloud Storage ini. Silahkan masukkan path / lokasi  yang akan ");

        jButton1.setText("Pilih Folder");

        jLabel32.setText("digunakan!");

        javax.swing.GroupLayout EditPathLayout = new javax.swing.GroupLayout(EditPath);
        EditPath.setLayout(EditPathLayout);
        EditPathLayout.setHorizontalGroup(
            EditPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPathLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(EditPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(EditPathLayout.createSequentialGroup()
                            .addComponent(txt_pathFolder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1))
                        .addComponent(jLabel31)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        EditPathLayout.setVerticalGroup(
            EditPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPathLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pathFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(436, Short.MAX_VALUE))
        );

        EditPath.setBounds(0, 0, 1050, 510);
        LayerGUI.add(EditPath, javax.swing.JLayeredPane.DEFAULT_LAYER);

        informasi.setText("Information");

        mnItem_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/user.png"))); // NOI18N
        mnItem_profile.setText("Profile");
        mnItem_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItem_profileActionPerformed(evt);
            }
        });
        informasi.add(mnItem_profile);

        menu.add(informasi);

        data.setText("Data");

        mnItem_komputer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/komputer.png"))); // NOI18N
        mnItem_komputer.setText("Data Komputer");
        mnItem_komputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItem_komputerActionPerformed(evt);
            }
        });
        data.add(mnItem_komputer);

        mnItem_server.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/server.png"))); // NOI18N
        mnItem_server.setText("Data Server");
        mnItem_server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItem_serverActionPerformed(evt);
            }
        });
        data.add(mnItem_server);

        mnItem_archive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/archive.png"))); // NOI18N
        mnItem_archive.setText("Data Archive");
        mnItem_archive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItem_archiveActionPerformed(evt);
            }
        });
        data.add(mnItem_archive);

        menu.add(data);

        menu_bantuan.setText("Bantuan");

        mnItem_bantuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/help.png"))); // NOI18N
        mnItem_bantuan.setText("Bantuan Penggunaan");
        menu_bantuan.add(mnItem_bantuan);

        mnItem_aboutMe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/user.png"))); // NOI18N
        mnItem_aboutMe.setText("Tentang Pembuat");
        menu_bantuan.add(mnItem_aboutMe);

        menu.add(menu_bantuan);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayerGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayerGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1056)/2, (screenSize.height-566)/2, 1056, 566);
    }// </editor-fold>//GEN-END:initComponents

    public void pushInfo(String nama,String email,String hp){
        txt_beranda_nama.setText(nama);
        
        //set Info pada halaman profile
        txt_profile_nama.setText(nama);
        txt_profileNama.setText(nama);
        txt_profileEmail.setText(email);
        txt_profileHP.setText(hp);
    }
    
    public void pushLastUsed(String id) throws SQLException{
        get_data file=new get_data();
        idSession=id;
        file.deletedListClient(id); //hapus database listClient 
        txt_profileFile.setText(file.get_lastUsed(id).getFile()+"");
        txt_profileFolder.setText(file.get_lastUsed(id).getFolder()+"");
        txt_profileSize.setText(file.get_lastUsed(id).getSize());
    }
    
    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        // TODO add your handling code here:
        //LayerGUI.moveToFront(Beranda);
    }//GEN-LAST:event_fileActionPerformed

    private void mnItem_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItem_profileActionPerformed
        // TODO add your handling code here:
        LayerGUI.moveToFront(Profile);
        Profile.setVisible(true);
        dataClient.setVisible(false);
        dataServer.setVisible(false);
        bantuan.setVisible(false);
        beranda.setVisible(false);
        EditPath.setVisible(false);
    }//GEN-LAST:event_mnItem_profileActionPerformed

    private void mnItem_komputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItem_komputerActionPerformed
        // TODO add your handling code here:
        LayerGUI.moveToFront(dataClient);
        dataClient.setVisible(true);
        dataServer.setVisible(false);
        bantuan.setVisible(false);
        Profile.setVisible(false);
        beranda.setVisible(false);
        EditPath.setVisible(false);  
        
    }//GEN-LAST:event_mnItem_komputerActionPerformed

    private void mnItem_serverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItem_serverActionPerformed
        // TODO add your handling code here:
        LayerGUI.moveToFront(dataServer);
        dataServer.setVisible(true);
        dataClient.setVisible(false);
        bantuan.setVisible(false);
        Profile.setVisible(false);
        beranda.setVisible(false);
        EditPath.setVisible(false);
    }//GEN-LAST:event_mnItem_serverActionPerformed

    private void mnItem_archiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItem_archiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnItem_archiveActionPerformed

    private void btn_listClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listClientActionPerformed
        // TODO add your handling code here:
        get_data file=new get_data();
        String alamat = "";
        String alamat2 = "";
        try {
            alamat = file.get_path(idSession).getPath()+"";
            alamat2=alamat.replaceAll("'\'", "/");
            System.out.println(alamat2);
        } catch (SQLException ex) {
            Logger.getLogger(Beranda.class.getName()).log(Level.SEVERE, null, ex);
        }
            File aFile = new File(alamat2);
            TableModel tab=new t_modelClient(d_listPC.prosesClient(aFile,idSession));
            t_listClient.setModel(tab);
            TableColumn column;
            column = t_listClient.getColumnModel().getColumn(0);
            column.setPreferredWidth(10);
            column = t_listClient.getColumnModel().getColumn(1);
            column.setPreferredWidth(500);
            column = t_listClient.getColumnModel().getColumn(2);
            column.setPreferredWidth(100);
            column = t_listClient.getColumnModel().getColumn(3);
            column.setPreferredWidth(50);
            column = t_listClient.getColumnModel().getColumn(4);
            column.setPreferredWidth(50);
            column = t_listClient.getColumnModel().getColumn(5);
            column.setPreferredWidth(50);
            
            System.out.println(t_listClient.getRowCount());
            btn_listClient.setEnabled(false);
    }//GEN-LAST:event_btn_listClientActionPerformed

    private void btn_listServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listServerActionPerformed
        // TODO add your handling code here:
        get_data file=new get_data();
        file.deletedListServer(idSession);
        testConnectionFtp kon = new testConnectionFtp();
        try {
            kon.getInfoFTP(file.get_accountFTP(idSession).getUser(), file.get_accountFTP(idSession).getUser());
        } catch (SQLException ex) {
            Logger.getLogger(Beranda.class.getName()).log(Level.SEVERE, null, ex);
        }

            //File aFile = new File(alamat2);
            TableModel tab;
        try {
            try {
                tab = new t_modelClient(d_listServer.prosesServer("",idSession,file.get_accountFTP(idSession).getUser(),file.get_accountFTP(idSession).getPass(),file.get_accountFTP(idSession).getHost()));
                t_listServer.setModel(tab);
            } catch (SQLException ex) {
                Logger.getLogger(Beranda.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(Beranda.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            TableColumn column;
            column = t_listServer.getColumnModel().getColumn(0);
            column.setPreferredWidth(10);
            column = t_listServer.getColumnModel().getColumn(1);
            column.setPreferredWidth(500);
            column = t_listServer.getColumnModel().getColumn(2);
            column.setPreferredWidth(100);
            column = t_listServer.getColumnModel().getColumn(3);
            column.setPreferredWidth(50);
            column = t_listServer.getColumnModel().getColumn(4);
            column.setPreferredWidth(50);
            column = t_listServer.getColumnModel().getColumn(5);
            column.setPreferredWidth(50);
            
            System.out.println(t_listServer.getRowCount());
            btn_listServer.setEnabled(false);
    }//GEN-LAST:event_btn_listServerActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EditPath;
    private javax.swing.JLayeredPane LayerGUI;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel bantuan;
    private javax.swing.JPanel beranda;
    private javax.swing.JButton btn_listClient;
    private javax.swing.JButton btn_listServer;
    private javax.swing.JMenu data;
    private javax.swing.JPanel dataClient;
    private javax.swing.JPanel dataServer;
    private javax.swing.JMenu informasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu_bantuan;
    private javax.swing.JMenuItem mnItem_aboutMe;
    private javax.swing.JMenuItem mnItem_archive;
    private javax.swing.JMenuItem mnItem_bantuan;
    private javax.swing.JMenuItem mnItem_komputer;
    private javax.swing.JMenuItem mnItem_profile;
    private javax.swing.JMenuItem mnItem_server;
    private javax.swing.JTable t_listClient;
    private javax.swing.JTable t_listServer;
    private javax.swing.JLabel txt_beranda_nama;
    private javax.swing.JTextField txt_pathFolder;
    private javax.swing.JLabel txt_profileEmail;
    private javax.swing.JLabel txt_profileFile;
    private javax.swing.JLabel txt_profileFolder;
    private javax.swing.JLabel txt_profileHP;
    private javax.swing.JLabel txt_profileNama;
    private javax.swing.JLabel txt_profileSize;
    private javax.swing.JLabel txt_profile_nama;
    // End of variables declaration//GEN-END:variables
}
